import numpy as np

STATIONARY, NOT_STATIONARY = range(2)
STATIONARY_CHECK_LEN = 10
EULER_INIT_LEN = 5
GRAVITY = 9.8
ACC_NORM_THRESHOLD = 0.8
GYR_NORM_THRESHOLD = 1.7 * 180 / np.pi
[SENSOR_FOOT, SENSOR_BACK] = range(2)
stance_status = [EARLY_STANCE, MIDDLE_STANCE, LATE_STANCE, SWING] = range(4)

